//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CargoRecieving
    {
        public CargoRecieving()
        {
            this.CargoDetails = new HashSet<CargoDetail>();
        }
    
        public long CargoReceiveId { get; set; }
        public int CustId { get; set; }
        public string SLNo { get; set; }
        public Nullable<System.DateTime> ReceivingDate { get; set; }
        public Nullable<int> ShipperId { get; set; }
        public Nullable<int> ConsigneeId { get; set; }
        public Nullable<int> FredForwarderId { get; set; }
        public Nullable<int> ClearForwarderId { get; set; }
        public string EFRNo { get; set; }
        public Nullable<System.DateTime> EFRDate { get; set; }
        public Nullable<System.DateTime> DocReceiveDate { get; set; }
        public Nullable<int> Lot { get; set; }
        public Nullable<System.DateTime> LotClosingDate { get; set; }
        public Nullable<int> Location { get; set; }
        public Nullable<int> CommodityId { get; set; }
        public Nullable<int> Destination { get; set; }
        public string DCode { get; set; }
        public Nullable<int> PORId { get; set; }
        public Nullable<int> VAT { get; set; }
        public Nullable<int> ReceivedBy { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public string Remarks { get; set; }
    
        public virtual ICollection<CargoDetail> CargoDetails { get; set; }
    }
}
