//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CargoDetail
    {
        public CargoDetail()
        {
            this.StuffingDetails = new HashSet<StuffingDetail>();
        }
    
        public long CargoDetailsId { get; set; }
        public Nullable<long> CargoReceiveId { get; set; }
        public string CartoonId { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public Nullable<bool> IsPCS { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<bool> IsCBM { get; set; }
        public Nullable<bool> IsKGs { get; set; }
        public Nullable<bool> IsGarmentItem { get; set; }
        public Nullable<int> Packages { get; set; }
        public Nullable<int> Pieces { get; set; }
        public Nullable<decimal> CubicMeter { get; set; }
        public Nullable<decimal> CargoWeight { get; set; }
        public string SONumber { get; set; }
        public string PONumber { get; set; }
        public string Style { get; set; }
        public string Item { get; set; }
        public string TPN { get; set; }
        public string REF { get; set; }
        public string CAT { get; set; }
        public string DIV { get; set; }
        public string DEPT { get; set; }
        public string InvoiceNo { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsStuffed { get; set; }
    
        public virtual CargoRecieving CargoRecieving { get; set; }
        public virtual ICollection<StuffingDetail> StuffingDetails { get; set; }
    }
}
