//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChartOfService
    {
        public ChartOfService()
        {
            this.ClientBillSetups = new HashSet<ClientBillSetup>();
        }
    
        public int ServiceId { get; set; }
        public Nullable<int> CateId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string ServiceCode { get; set; }
        public string ServiceName { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<bool> IsTransaction { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> EntryUser { get; set; }
    
        public virtual ChartOfServiceCategory ChartOfServiceCategory { get; set; }
        public virtual ICollection<ClientBillSetup> ClientBillSetups { get; set; }
    }
}
