//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChartOfAccount
    {
        public int ID { get; set; }
        public string code { get; set; }
        public string ac_name { get; set; }
        public int parent { get; set; }
        public string type { get; set; }
        public int levelno { get; set; }
        public Nullable<decimal> open_bal { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public int active { get; set; }
        public Nullable<int> CreatId { get; set; }
    }
}
