//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientBillSetup
    {
        public int BillSetupId { get; set; }
        public int ServiceId { get; set; }
        public Nullable<int> CustId { get; set; }
        public Nullable<int> Amend { get; set; }
        public Nullable<int> SizeId { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> TrailerId { get; set; }
        public Nullable<int> Location { get; set; }
        public Nullable<int> Tariff { get; set; }
        public Nullable<System.DateTime> Entrydate { get; set; }
    
        public virtual ChartOfService ChartOfService { get; set; }
        public virtual ContainerSize ContainerSize { get; set; }
    }
}
