//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Container
    {
        public int ContainerId { get; set; }
        public string ContainerNumber { get; set; }
        public Nullable<int> ContainerSizeId { get; set; }
        public Nullable<int> ContainerTypeId { get; set; }
        public string ISO_Number { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    }
}
