//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContainerType
    {
        public ContainerType()
        {
            this.CSDContGateInOuts = new HashSet<CSDContGateInOut>();
            this.IGMImportDetails = new HashSet<IGMImportDetail>();
            this.ISOMappings = new HashSet<ISOMapping>();
        }
    
        public int ContainerTypeId { get; set; }
        public string ContainerTypeName { get; set; }
    
        public virtual ICollection<CSDContGateInOut> CSDContGateInOuts { get; set; }
        public virtual ICollection<IGMImportDetail> IGMImportDetails { get; set; }
        public virtual ICollection<ISOMapping> ISOMappings { get; set; }
    }
}
