//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSDBillSummary
    {
        public int Id { get; set; }
        public string SummaryRefNo { get; set; }
        public int CustId { get; set; }
        public string CustomerCode { get; set; }
        public string Size { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> BillFrom { get; set; }
        public Nullable<System.DateTime> BillTo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> BillType { get; set; }
    }
}
