//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSDContGateInOut
    {
        public long ContainerGateEntryId { get; set; }
        public int CustId { get; set; }
        public Nullable<long> RefNo { get; set; }
        public Nullable<bool> IsFromIGMImport { get; set; }
        public string ContNo { get; set; }
        public Nullable<bool> InPermission { get; set; }
        public Nullable<int> ContType { get; set; }
        public Nullable<int> ContSize { get; set; }
        public string ISO { get; set; }
        public string ExpVssl { get; set; }
        public string ImpVssl { get; set; }
        public string RotExp { get; set; }
        public string RotImp { get; set; }
        public string ChallanNo { get; set; }
        public string ChallanOut { get; set; }
        public Nullable<int> TrailerIn { get; set; }
        public Nullable<int> TrailerOut { get; set; }
        public string TrailerInNo { get; set; }
        public string TrailerOutNo { get; set; }
        public Nullable<int> HaulierIn { get; set; }
        public Nullable<int> HaulierOut { get; set; }
        public Nullable<int> DepotTo { get; set; }
        public Nullable<int> DepotFrom { get; set; }
        public string BillTo { get; set; }
        public Nullable<int> UserIdGateOut { get; set; }
        public Nullable<int> UserIdGateIn { get; set; }
        public Nullable<System.DateTime> DateIn { get; set; }
        public Nullable<System.DateTime> DateOut { get; set; }
        public Nullable<int> ContInCondition { get; set; }
        public Nullable<int> ContOutCondition { get; set; }
        public Nullable<int> LoadEmptyStatus { get; set; }
        public Nullable<int> LoadEmptyStatusOut { get; set; }
        public Nullable<System.DateTime> DumpingDate { get; set; }
        public string BookingNoDump { get; set; }
        public string BookingNoOut { get; set; }
        public string RemarkIn { get; set; }
        public string RemarkOut { get; set; }
        public Nullable<int> InOutStatus { get; set; }
        public Nullable<System.DateTime> StuffingDate { get; set; }
    
        public virtual ContainerSize ContainerSize { get; set; }
        public virtual ContainerType ContainerType { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Haulier Haulier { get; set; }
    }
}
