//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSDGateInUPComing
    {
        public int Id { get; set; }
        public Nullable<int> MLOID { get; set; }
        public string MLOCode { get; set; }
        public string ContainerNo { get; set; }
        public Nullable<int> SizeId { get; set; }
        public string SizeName { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Type { get; set; }
        public string RotationNumber { get; set; }
        public string ImportVasselName { get; set; }
    }
}
