//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSDMonthlyBillProcessTrack
    {
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> BillfromDate { get; set; }
        public Nullable<System.DateTime> BillToDate { get; set; }
        public string MonthOffYear { get; set; }
        public string Year { get; set; }
        public string Entrydate { get; set; }
        public string UserId { get; set; }
    }
}
