//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.CSDContGateInOuts = new HashSet<CSDContGateInOut>();
            this.IGMImports = new HashSet<IGMImport>();
        }
    
        public int CustomerId { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> AgentId { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string RDA { get; set; }
        public string Type { get; set; }
        public string CarrierCode { get; set; }
        public Nullable<int> isNoBill { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> BillProcessMonthly { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual ICollection<CSDContGateInOut> CSDContGateInOuts { get; set; }
        public virtual ICollection<IGMImport> IGMImports { get; set; }
    }
}
