//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportBillDetail
    {
        public long ID { get; set; }
        public int BillId { get; set; }
        public string EFRNo { get; set; }
        public int ServiceId { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<int> TypeId { get; set; }
        public int Quantity { get; set; }
        public decimal Rate { get; set; }
        public decimal Total { get; set; }
        public Nullable<bool> IsVAT { get; set; }
    
        public virtual ExportBill ExportBill { get; set; }
    }
}
