//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportBill
    {
        public ExportBill()
        {
            this.ExportBillDetails = new HashSet<ExportBillDetail>();
        }
    
        public int ID { get; set; }
        public int BillType { get; set; }
        public string RefNo { get; set; }
        public string EFRNo { get; set; }
        public Nullable<int> ShipperId { get; set; }
        public Nullable<int> CandFAgentId { get; set; }
        public Nullable<int> CustId { get; set; }
        public Nullable<int> FredForderId { get; set; }
        public decimal TotalAmount { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<bool> IsPercentage { get; set; }
        public Nullable<decimal> VatPercent { get; set; }
        public Nullable<decimal> VatAmount { get; set; }
        public decimal GrandTotal { get; set; }
        public System.DateTime BillPrepareDate { get; set; }
        public int SavedById { get; set; }
        public Nullable<int> EditById { get; set; }
    
        public virtual ICollection<ExportBillDetail> ExportBillDetails { get; set; }
    }
}
