//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormList
    {
        public FormList()
        {
            this.UserPermissionMappings = new HashSet<UserPermissionMapping>();
        }
    
        public int FormId { get; set; }
        public string FormName { get; set; }
    
        public virtual ICollection<UserPermissionMapping> UserPermissionMappings { get; set; }
    }
}
