//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Haulier
    {
        public Haulier()
        {
            this.CSDContGateInOuts = new HashSet<CSDContGateInOut>();
        }
    
        public int HaulierId { get; set; }
        public string HaulierNo { get; set; }
    
        public virtual ICollection<CSDContGateInOut> CSDContGateInOuts { get; set; }
    }
}
