//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class IGMContGateInOut
    {
        public long IGMContGateInOutId { get; set; }
        public long IGMDetailsId { get; set; }
        public Nullable<long> RefNo { get; set; }
        public Nullable<int> CPALockId { get; set; }
        public Nullable<int> MLIId { get; set; }
        public Nullable<int> TrailerId { get; set; }
        public string TrailerNumber { get; set; }
        public Nullable<int> HaulierInNo { get; set; }
        public Nullable<int> GateInCondition { get; set; }
        public Nullable<int> GateOutCondition { get; set; }
        public Nullable<System.DateTime> GateInDate { get; set; }
        public Nullable<System.DateTime> GateOutDate { get; set; }
        public Nullable<int> DeliveryType { get; set; }
        public Nullable<int> ClearingForwarderId { get; set; }
        public Nullable<int> FreightForwarderId { get; set; }
        public string RemarksIn { get; set; }
        public string RemarksOut { get; set; }
        public Nullable<int> GateInUserId { get; set; }
        public Nullable<int> GateOutUserId { get; set; }
    
        public virtual IGMImportDetail IGMImportDetail { get; set; }
    }
}
