//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class IGMImportDetail
    {
        public IGMImportDetail()
        {
            this.IGMContGateInOuts = new HashSet<IGMContGateInOut>();
        }
    
        public long IGMDetailsId { get; set; }
        public Nullable<int> IGMImportId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ContainerNo { get; set; }
        public string SealNo { get; set; }
        public Nullable<int> SizeId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string ISO { get; set; }
        public Nullable<int> InOutStatus { get; set; }
    
        public virtual ContainerSize ContainerSize { get; set; }
        public virtual ContainerType ContainerType { get; set; }
        public virtual ICollection<IGMContGateInOut> IGMContGateInOuts { get; set; }
        public virtual IGMImport IGMImport { get; set; }
    }
}
