//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class IGMImport
    {
        public IGMImport()
        {
            this.IGMImportDetails = new HashSet<IGMImportDetail>();
        }
    
        public int IGMImportId { get; set; }
        public string ReferanceNumber { get; set; }
        public string BLnumber { get; set; }
        public string LineNo { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> ImporterId { get; set; }
        public Nullable<int> ClearandForwId { get; set; }
        public Nullable<int> FrieghtForwId { get; set; }
        public Nullable<int> VesselId { get; set; }
        public string Rotation { get; set; }
        public Nullable<int> CommodityId { get; set; }
        public Nullable<int> NumberofPackage { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public Nullable<int> PortofDischargeId { get; set; }
        public Nullable<int> PortofDeliveryId { get; set; }
        public Nullable<int> BoxQuantity { get; set; }
        public Nullable<int> BoxReceived { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual UnintOfMeasure UnintOfMeasure { get; set; }
        public virtual Vessel Vessel { get; set; }
        public virtual ICollection<IGMImportDetail> IGMImportDetails { get; set; }
    }
}
