//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImpDetentionCharg
    {
        public int ID { get; set; }
        public int SlabId { get; set; }
        public int SizeId { get; set; }
        public Nullable<int> SlabDays { get; set; }
        public Nullable<int> TotalDays { get; set; }
        public Nullable<int> RateInTk { get; set; }
        public Nullable<double> RateInDlr { get; set; }
    }
}
