//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISOMapping
    {
        public int ID { get; set; }
        public int SizeId { get; set; }
        public int TypeId { get; set; }
        public string ISOCode { get; set; }
    
        public virtual ContainerSize ContainerSize { get; set; }
        public virtual ContainerType ContainerType { get; set; }
    }
}
