//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoneyReceipt
    {
        public MoneyReceipt()
        {
            this.MoneyReceiptDetails = new HashSet<MoneyReceiptDetail>();
        }
    
        public int ID { get; set; }
        public string MoneyReceiptNo { get; set; }
        public string ReferenceNo { get; set; }
        public int MRType { get; set; }
        public Nullable<int> CandFAgentId { get; set; }
        public Nullable<int> ImporterId { get; set; }
        public Nullable<int> ShipperId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string RiskbondNo { get; set; }
        public Nullable<System.DateTime> RBDate { get; set; }
        public Nullable<int> PaymentOption { get; set; }
        public Nullable<int> BankId { get; set; }
        public string ChqPayorderNo { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public decimal TotalAmount { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<bool> IsPercentage { get; set; }
        public Nullable<decimal> VatPercent { get; set; }
        public decimal GrandTotal { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> SavedById { get; set; }
    
        public virtual ICollection<MoneyReceiptDetail> MoneyReceiptDetails { get; set; }
    }
}
