//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoneyReceiptDetail
    {
        public long ID { get; set; }
        public Nullable<int> MoneyReceiptId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual MoneyReceipt MoneyReceipt { get; set; }
    }
}
