//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatternConfig
    {
        public int AutoId { get; set; }
        public string ConfigType { get; set; }
        public bool IsAutoGenCode { get; set; }
        public string Prefix1 { get; set; }
        public string Prefix2 { get; set; }
        public string Prefix3 { get; set; }
        public string Suffix1 { get; set; }
        public string Suffix2 { get; set; }
        public string Delimiter { get; set; }
        public int DigitNumber { get; set; }
        public int CurrentNumber { get; set; }
    }
}
