//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Port
    {
        public int PortOfLandId { get; set; }
        public string PortCode { get; set; }
        public string PortName { get; set; }
        public string PortCountry { get; set; }
    }
}
