//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceDetail
    {
        public int ServiceDetailsId { get; set; }
        public int ServiceId { get; set; }
        public Nullable<int> ContSizeId { get; set; }
        public Nullable<double> RateTk { get; set; }
        public Nullable<double> RateDollar { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
