//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.ServiceDetails = new HashSet<ServiceDetail>();
        }
    
        public int ID { get; set; }
        public string ServiceName { get; set; }
        public Nullable<int> ServiceCategory { get; set; }
    
        public virtual ICollection<ServiceDetail> ServiceDetails { get; set; }
    }
}
