//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class StuffingDetail
    {
        public long StuffingDetailsId { get; set; }
        public long CargoDetailsId { get; set; }
        public int CustId { get; set; }
        public string ContainerNo { get; set; }
        public Nullable<int> SizeId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public long RefNo { get; set; }
        public long CSDGateEntryId { get; set; }
        public string SealNo { get; set; }
        public Nullable<int> TareWT { get; set; }
        public Nullable<bool> IsSub { get; set; }
        public Nullable<bool> IsReferContainer { get; set; }
        public Nullable<System.DateTime> PluginDate { get; set; }
        public Nullable<System.DateTime> PTIDate { get; set; }
        public Nullable<int> StuffCategory { get; set; }
        public Nullable<int> DayNightShift { get; set; }
        public Nullable<int> Location { get; set; }
        public string BookingNo { get; set; }
        public Nullable<int> Status { get; set; }
        public string VGMWeight { get; set; }
        public string CarrierName { get; set; }
        public string ExpNo { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public Nullable<int> NegotiatingBank { get; set; }
        public Nullable<int> PortofLoading { get; set; }
        public Nullable<int> PortofDischarge { get; set; }
        public int StuffedById { get; set; }
        public System.DateTime StuffingDate { get; set; }
        public string UpdateById { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual CargoDetail CargoDetail { get; set; }
    }
}
