//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDocumentstatu
    {
        public int DocumentId { get; set; }
        public Nullable<int> CatergoryId { get; set; }
        public string Documentstatustype { get; set; }
    }
}
