//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrailerNumber
    {
        public int TrailerNumberId { get; set; }
        public int TrailerId { get; set; }
        public string TrailerNumber1 { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    
        public virtual Trailer Trailer { get; set; }
    }
}
