//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trailer
    {
        public Trailer()
        {
            this.TrailerNumbers = new HashSet<TrailerNumber>();
        }
    
        public int TrailerId { get; set; }
        public string TrailerCode { get; set; }
        public string TrailerName { get; set; }
        public string OwnerName { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<TrailerNumber> TrailerNumbers { get; set; }
    }
}
