//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRReportData
    {
        public int ID { get; set; }
        public string TRNo { get; set; }
        public Nullable<int> CargoReceivingId { get; set; }
        public Nullable<int> MLOId { get; set; }
        public string EFRNo { get; set; }
        public Nullable<int> PortofDeliveryId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
