//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnintOfMeasure
    {
        public UnintOfMeasure()
        {
            this.IGMImports = new HashSet<IGMImport>();
        }
    
        public int UnitOfMeasureId { get; set; }
        public string UnitOfMeasureName { get; set; }
    
        public virtual ICollection<IGMImport> IGMImports { get; set; }
    }
}
