//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPermissionMapping
    {
        public int Id { get; set; }
        public int RoleId { get; set; }
        public int FormId { get; set; }
        public Nullable<bool> View { get; set; }
        public Nullable<bool> Save { get; set; }
        public Nullable<bool> Edit { get; set; }
        public Nullable<bool> Delete { get; set; }
    
        public virtual FormList FormList { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
