//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vessel
    {
        public Vessel()
        {
            this.IGMImports = new HashSet<IGMImport>();
        }
    
        public int VesselId { get; set; }
        public string VesselCode { get; set; }
        public string VesselName { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    
        public virtual ICollection<IGMImport> IGMImports { get; set; }
    }
}
