//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherDetail
    {
        public long VoucherDtlsId { get; set; }
        public int VoucherMstrId { get; set; }
        public Nullable<int> COAId { get; set; }
        public decimal Amount { get; set; }
        public string DrCr { get; set; }
        public string TranMode { get; set; }
    
        public virtual VoucherMaster VoucherMaster { get; set; }
    }
}
