//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGISTIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_DISTINCTGATEENTRY_STUFFING
    {
        public long CSDGateEntryId { get; set; }
        public string BookingNo { get; set; }
        public System.DateTime StuffingDate { get; set; }
        public string SealNo { get; set; }
    }
}
